import { useCallback, useEffect, useRef, useState } from 'react';
import { Mail as MailIcon, CalendarDays, Settings as SettingsIcon, Search, Plus, ChevronDown, ChevronRight, Inbox, Send, FileText, Star, Archive, Trash2, Folder, FolderPlus, PanelRight, Sun, Moon, RefreshCw, Tag, Users, Sparkles, X, MoreHorizontal, Reply, Forward, MailOpen, AlertCircle, Check, Command, Paperclip, Loader2, ArrowDown, CircleHelp, ShieldAlert } from 'lucide-react';
import type { Account, Boot, Calendar, CalendarEvent, CalendarSearch, CalendarResults, Category, Compose, Config, Folder as MailFolder, Mail, MailRef, Mutation, UndoEntry } from './types';
import { getAPI, liveAPI } from './api';
import { addDays, categoryLabel, initials, keyOf, localDate, mergeMailPage, selectRows, weekStart } from './domain';
import { Composer, Crest, EventEditor, IconButton, MailContent, MiniCalendar, Modal, Settings } from './components';
import { Agenda, CalendarView } from './CalendarView';
import { CalendarSearchResults } from './CalendarSearchResults';
import { defaultCalendarRange } from './ai';
const params = new URLSearchParams(location.search); const messageRef = params.has('message') ? { id: params.get('message')!, accountId: params.get('account')! } : null;
const systemFolders = [{ id: 'INBOX', name: 'Inbox', icon: Inbox }, { id: 'STARRED', name: 'Starred', icon: Star }, { id: 'SENT', name: 'Sent', icon: Send }, { id: 'DRAFT', name: 'Drafts', icon: FileText }, { id: 'ALL', name: 'All mail', icon: Archive }, { id: 'TRASH', name: 'Trash', icon: Trash2 }, { id: 'SPAM', name: 'Spam', icon: ShieldAlert }];
const defaultConfig: Config = { googleConfigured: false, geminiConfigured: false, geminiModel: 'gemini-3.8-flash' };
const dragType = 'application/x-raizormail';
export function App() {
  const [theme, setTheme] = useState(localStorage.getItem('raizormail-theme') || 'dark');
  const [preview, setPreview] = useState(localStorage.getItem('raizormail-preview') === 'true');
  const [agenda, setAgenda] = useState(localStorage.getItem('raizormail-agenda') !== 'false');
  const [paneWidth, setPaneWidth] = useState(Number(localStorage.getItem('raizormail-pane-width')) || 480);
  const [demo, setDemo] = useState(messageRef ? params.get('demo') === '1' : localStorage.getItem('raizormail-demo') !== 'false');
  const [ready, setReady] = useState(false); const [accounts, setAccounts] = useState<Account[]>([]); const [connected, setConnected] = useState<Account[]>([]); const [config, setConfig] = useState(defaultConfig);
  const [accountId, setAccountId] = useState(''); const [view, setView] = useState<'mail' | 'calendar'>('mail'); const [folder, setFolder] = useState('INBOX'); const [category, setCategory] = useState<Category>('primary');
  const [folders, setFolders] = useState<MailFolder[]>([]); const [messages, setMessages] = useState<Mail[]>([]); const [selected, setSelected] = useState<string[]>([]); const [anchor, setAnchor] = useState<string | null>(null); const [activeMail, setActiveMail] = useState<Mail | null>(null);
  const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [ai, setAi] = useState(true); const [searching, setSearching] = useState(false); const [unreadOnly, setUnreadOnly] = useState(false);
  const [calendarSearch, setCalendarSearch] = useState<CalendarSearch | null>(null);
  const [calendarResults, setCalendarResults] = useState<CalendarResults>({ events: [], nextPageTokens: {} });
  const searchGeneration = useRef(0);
  useEffect(() => { searchGeneration.current++; setSearching(false); setSearch(''); setQuery(''); setCalendarSearch(null); setCalendarResults({ events: [], nextPageTokens: {} }); }, [view, accountId, demo]);
  const [loading, setLoading] = useState(false); const [busy, setBusy] = useState(false); const [pageTokens, setPageTokens] = useState<Record<string, string>>({}); const [warnings, setWarnings] = useState<string[]>([]);
  const [calendars, setCalendars] = useState<Calendar[]>([]); const [events, setEvents] = useState<CalendarEvent[]>([]); const [date, setDate] = useState(new Date());
  const [settings, setSettings] = useState(false); const [viewMenu, setViewMenu] = useState(false); const [moveMenu, setMoveMenu] = useState(false); const [folderModal, setFolderModal] = useState(false); const [newFolder, setNewFolder] = useState(''); const [help, setHelp] = useState(false);
  const [compose, setCompose] = useState<Compose | null>(null); const [eventDraft, setEventDraft] = useState<CalendarEvent | null>(null); const [toast, setToast] = useState<{ text: string; error?: boolean; undo?: UndoEntry[] } | null>(null); const [syncTime, setSyncTime] = useState<Date | null>(null);
  const [dragGhost, setDragGhost] = useState<{ x: number; y: number; count: number } | null>(null); const suppressClick = useRef(0); const dragCleanup = useRef<(() => void) | null>(null);
  useEffect(() => () => dragCleanup.current?.(), []);
  const viewMenuRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!viewMenu) return;
    const dismiss = (e: PointerEvent | FocusEvent) => { if (!viewMenuRef.current?.contains(e.target as Node)) setViewMenu(false); };
    const blur = () => setViewMenu(false);
    document.addEventListener('pointerdown', dismiss, true); document.addEventListener('focusin', dismiss); window.addEventListener('blur', blur);
    return () => { document.removeEventListener('pointerdown', dismiss, true); document.removeEventListener('focusin', dismiss); window.removeEventListener('blur', blur); };
  }, [viewMenu]);
  const searchRef = useRef<HTMLInputElement>(null); const generation = useRef(0); const eventGeneration = useRef(0); const api = getAPI(demo); const visible = messages.filter(m => !unreadOnly || m.unread); const selectedMails = messages.filter(m => selected.includes(keyOf(m))); const current = selectedMails.length === 1 ? selectedMails[0] : null;
  const notify = useCallback((text: string) => setToast({ text }), []); const error = useCallback((e: unknown) => setToast({ text: e instanceof Error ? e.message.replace(/^Error invoking remote method '[^']+': Error: /, '') : String(e), error: true }), []);
  const setDemoMode = (value: boolean) => { setDemo(value); localStorage.setItem('raizormail-demo', String(value)); setAccountId(''); setSelected([]); setMessages([]); setQuery(''); setSearch(''); setFolder('INBOX'); };
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('raizormail-theme', theme); }, [theme]);
  useEffect(() => { localStorage.setItem('raizormail-preview', String(preview)); }, [preview]);
  useEffect(() => { localStorage.setItem('raizormail-agenda', String(agenda)); }, [agenda]);
  useEffect(() => { if (!toast || toast.error || toast.undo) return; const t = setTimeout(() => setToast(null), 5500); return () => clearTimeout(t); }, [toast]);
  useEffect(() => { let cancelled = false; (async () => { let boot: Boot = { accounts: [], config: defaultConfig }; if (window.desktop) boot = await liveAPI.bootstrap(); if (cancelled) return; setConnected(boot.accounts); setConfig(boot.config); const mode = messageRef ? params.get('demo') === '1' : !boot.accounts.length || localStorage.getItem('raizormail-demo') === 'true' || !window.desktop; setDemo(mode); const initial = await getAPI(mode).bootstrap(); if (!cancelled) { setAccounts(initial.accounts); setReady(true); } })().catch(error); return () => { cancelled = true; }; }, [error]);
  useEffect(() => { if (!ready) return; let cancelled = false; api.bootstrap().then(b => { if (!cancelled) setAccounts(b.accounts); }).catch(error); if (!messageRef) api.listFolders().then(f => { if (!cancelled) setFolders(f); }).catch(error); api.listCalendars().then(c => { if (!cancelled) setCalendars(c); }).catch(error); return () => { cancelled = true; }; }, [demo, ready, api, error]);
  const load = useCallback(async (more = false, silent = false) => {
    if (!ready) return; const request = ++generation.current; if (!silent) setLoading(true);
    try { if (messageRef) { const m = await api.getMessage(messageRef); if (request === generation.current) setActiveMail(m); return; }
      const page = await api.listMessages({ accountId: accountId || undefined, folder, category, query, ...(more ? { pageTokens } : {}) });
      if (request !== generation.current) return;
      setMessages(old => mergeMailPage(old, page, more));
      setPageTokens(old => ({ ...Object.fromEntries(Object.entries(old).filter(([id]) => page.failedAccountIds?.includes(id))), ...page.nextPageTokens }));
      setWarnings(page.errors || []); if (!page.errors?.length) setSyncTime(new Date());
    } catch (e) { if (request === generation.current) error(e); } finally { if (request === generation.current) setLoading(false); }
  }, [ready, api, accountId, folder, category, query, error, pageTokens]);
  const loadRef = useRef(load); loadRef.current = load;
  const loadEvents = useCallback(async () => { if (!ready || messageRef) return; const version = ++eventGeneration.current; const start = weekStart(date); try { const result = await api.listEvents(start.toISOString(), addDays(start, 8).toISOString()); if (version === eventGeneration.current) { setEvents(result.events); if (result.errors?.length) error(new Error(result.errors.join('\n'))); } } catch (e) { error(e); } }, [api, date, ready, error]);
  const eventsRef = useRef(loadEvents); eventsRef.current = loadEvents;
  useEffect(() => { setSelected([]); setAnchor(null); setMessages([]); void loadRef.current(); }, [accountId, folder, category, query, demo, ready]);
  useEffect(() => { void loadEvents(); }, [loadEvents]);
  useEffect(() => {
    if (!ready) return;
    let debounce: ReturnType<typeof setTimeout>; const scopes = new Set<string>();
    const refresh = (change?: { scope: 'mail' | 'calendar' }) => {
      scopes.add(change?.scope || 'all'); clearTimeout(debounce);
      debounce = setTimeout(() => {
        if (scopes.has('all') || scopes.has('mail')) void loadRef.current(false, true);
        if (!messageRef) {
          if (scopes.has('all') || scopes.has('calendar')) void eventsRef.current();
          if (scopes.has('all')) api.listFolders().then(setFolders).catch(error);
        }
        scopes.clear();
      }, 250);
    };
    const channel = new BroadcastChannel('raizormail'); channel.onmessage = () => refresh();
    const unsubscribe = window.desktop?.onChanged(refresh);
    // Only the mailbox window polls. Message windows receive change notifications.
    const interval = messageRef ? undefined : setInterval(() => refresh(), 60000);
    return () => { channel.close(); unsubscribe?.(); clearInterval(interval); clearTimeout(debounce); };
  }, [ready, api, error]);
  async function reconnect() { const b = await liveAPI.bootstrap(); setConnected(b.accounts); setConfig(b.config); if (b.accounts.length) { setDemoMode(false); setAccounts(b.accounts); } else { setDemoMode(true); } await loadRef.current(); }
  function select(m: Mail, e: React.MouseEvent) { if (Date.now() < suppressClick.current) return; const result = selectRows(visible.map(keyOf), selected, keyOf(m), anchor, e.metaKey || e.ctrlKey, e.shiftKey); setSelected(result.selected); setAnchor(result.anchor); }
  async function mutate(action: Omit<Mutation, 'refs'>, refs = selectedMails.map(m => ({ id: m.id, accountId: m.accountId })), quiet = false) {
    if (!refs.length) return; setBusy(true); try { const result = await api.mutate({ ...action, refs });
      if (!quiet && result.succeeded.length) { const verb = action.kind === 'trash' ? 'Moved to Trash' : action.kind === 'move' ? `Moved to ${action.target?.startsWith('CATEGORY_') ? action.target.replace('CATEGORY_', '').toLowerCase() : action.target}` : action.kind === 'archive' ? 'Archived' : action.kind === 'read' ? `Marked ${action.value ? 'read' : 'unread'}` : action.value ? 'Starred' : 'Unstarred'; setToast({ text: `${verb} · ${result.succeeded.length} message${result.succeeded.length === 1 ? '' : 's'}`, undo: result.undo }); }
      if (result.failed.length) setToast({ text: `${result.succeeded.length} succeeded; ${result.failed.length} failed. ${result.failed[0].error}`, error: true, undo: result.undo.length ? result.undo : undefined });
      if (['trash', 'move', 'archive'].includes(action.kind)) setSelected(s => s.filter(k => !result.succeeded.includes(k)));
      // The shared change notification refreshes all windows once.
      return result;
    } catch (e) { error(e); } finally { setBusy(false); }
  }
  function openMail(m: Mail) {
    if (m.labels.includes('DRAFT')) { setBusy(true); Promise.all([api.getMessage(m), api.materializeAttachments(m)]).then(([draft, attachments]) => setCompose({ accountId: draft.accountId, to: draft.to, cc: draft.cc || '', bcc: draft.bcc || '', subject: draft.subject, text: draft.text, attachments, draftId: draft.draftId, threadId: draft.threadId })).catch(error).finally(() => setBusy(false)); return; }
    if (window.desktop) window.desktop.openMessage({ id: m.id, accountId: m.accountId }, demo).catch(error);
    else { const url = new URL(location.href); url.search = new URLSearchParams({ message: m.id, account: m.accountId, demo: String(Number(demo)) }).toString(); const popup = window.open(url, `mail-${keyOf(m)}`, 'popup,width=900,height=800'); if (!popup) { error(new Error('Allow pop-up windows to open emails, or use the Mac app.')); return; } }
    if (m.unread) void mutate({ kind: 'read', value: true }, [{ id: m.id, accountId: m.accountId }], true);
  }
  function newCompose(kind?: 'reply' | 'replyAll' | 'forward', mail?: Mail) {
    const a = accounts.find(a => a.id === mail?.accountId) || accounts.find(a => a.id === accountId) || accounts[0]; if (!a) { setSettings(true); return; }
    const c: Compose = { accountId: a.id, to: '', cc: '', bcc: '', subject: '', text: '', attachments: [] };
    if (mail && kind) { c.subject = `${kind === 'forward' ? 'Fwd: ' : /^re:/i.test(mail.subject) ? '' : 'Re: '}${mail.subject}`; c.text = `\n\nOn ${new Date(mail.date).toLocaleString()}, ${mail.from} <${mail.fromEmail}> wrote:\n\n${(mail.text || mail.snippet).split('\n').map(l => `> ${l}`).join('\n')}`; if (kind !== 'forward') { c.to = mail.replyTo || mail.fromEmail; c.threadId = mail.threadId; c.inReplyTo = mail.messageId; c.references = [mail.references, mail.messageId].filter(Boolean).join(' '); if (kind === 'replyAll') c.cc = [mail.to, mail.cc].filter(Boolean).join(', ').split(',').filter(s => !s.toLowerCase().includes(a.email.toLowerCase()) && !s.includes(mail.fromEmail)).join(', '); } }
    if (kind === 'forward' && mail?.attachments.length) { setBusy(true); api.materializeAttachments(mail).then(attachments => setCompose({ ...c, attachments })).catch(error).finally(() => setBusy(false)); } else setCompose(c);
  }
  function newEvent(d = new Date(), mail?: Mail, mails?: Mail[]) {
    const calendar = calendars.find(c => c.writable && c.accountId === (mail?.accountId || accountId)) || calendars.find(c => c.writable); if (!calendar) { error(new Error('Connect a writable Google Calendar in Settings first.')); return; }
    const start = new Date(d); if (start.getHours() === 0 && start.getMinutes() === 0) start.setHours(9, 0, 0, 0); else if (!mail && localDate(d) === localDate(new Date()) && Math.abs(+d - Date.now()) < 1000) { start.setMinutes(0, 0, 0); start.setHours(start.getHours() + 1); }
    const source = mails || (mail ? [mail] : []); const notes = source.map(m => `Email: ${m.subject}\nFrom: ${m.from} <${m.fromEmail}>\n${m.text || m.snippet}${demo ? '' : `\n\nOpen in Gmail: https://mail.google.com/mail/u/?authuser=${encodeURIComponent(accounts.find(a => a.id === m.accountId)?.email || '')}#all/${m.threadId}`}`).join('\n\n———\n\n');
    setEventDraft({ id: '', accountId: calendar.accountId, calendarId: calendar.id, title: source.length > 1 ? `${source[0].subject} (+${source.length - 1} emails)` : mail?.subject || '', description: notes, location: '', start: start.toISOString(), end: new Date(start.getTime() + 3600000).toISOString(), color: calendar.color });
  }
  function pointerDrag(e: React.PointerEvent, mail: Mail) {
    if (e.button !== 0 || busy || (e.target as HTMLElement).closest('button')) return;
    const startX = e.clientX, startY = e.clientY;
    const keys = selected.includes(keyOf(mail)) ? selected : [keyOf(mail)];
    const mails = messages.filter(m => keys.includes(keyOf(m)));
    const refs = mails.map(m => ({ id: m.id, accountId: m.accountId }));
    let dragging = false; let target: HTMLElement | null = null;
    const element = e.currentTarget as HTMLElement; element.setPointerCapture(e.pointerId);
    function move(event: PointerEvent) {
      if (!dragging && Math.hypot(event.clientX - startX, event.clientY - startY) < 6) return;
      if (!dragging) { dragging = true; setSelected(keys); }
      event.preventDefault();
      setDragGhost({ x: event.clientX, y: event.clientY, count: keys.length });
      const next = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>('[data-drop-folder], [data-drop-date]') || null;
      if (target !== next) { target?.classList.remove('drag-over'); next?.classList.add('drag-over'); target = next; }
    }
    function cleanup() { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', up); window.removeEventListener('pointercancel', cancel); window.removeEventListener('blur', cancel); target?.classList.remove('drag-over'); setDragGhost(null); dragCleanup.current = null; }
    function cancel() { cleanup(); }
    function up(event: PointerEvent) {
      const destination = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>('[data-drop-folder], [data-drop-date]');
      cleanup(); if (!dragging) return; suppressClick.current = Date.now() + 350; event.preventDefault();
      const folderTarget = destination?.dataset.dropFolder, day = destination?.dataset.dropDate;
      if (folderTarget && (folderTarget !== folder || query)) void mutate(folderTarget === 'TRASH' ? { kind: 'trash' } : { kind: 'move', target: folderTarget, source: query ? 'SEARCH' : folder }, refs);
      else if (day) newEvent(new Date(day), mails[0], mails);
    }
    dragCleanup.current?.(); dragCleanup.current = cleanup;
    window.addEventListener('pointermove', move, { passive: false }); window.addEventListener('pointerup', up); window.addEventListener('pointercancel', cancel); window.addEventListener('blur', cancel);
  }
  function dragData(e: React.DragEvent): { refs: MailRef[]; source: string } | null { try { const d = JSON.parse(e.dataTransfer.getData(dragType)); return Array.isArray(d.refs) && d.refs.every((r: MailRef) => typeof r.id === 'string' && typeof r.accountId === 'string') ? d : null; } catch { return null; } }
  function folderDrop(e: React.DragEvent, target: string) { e.preventDefault(); e.currentTarget.classList.remove('drag-over'); const d = dragData(e); if (d && target !== d.source) void mutate(target === 'TRASH' ? { kind: 'trash' } : { kind: 'move', target, source: d.source }, d.refs); }
  async function calendarDrop(e: React.DragEvent, d: Date) { e.preventDefault(); const data = dragData(e); if (!data) return; try { const mails = await Promise.all(data.refs.map(ref => api.getMessage(ref))); newEvent(d, mails[0], mails); } catch (e) { error(e); } }
  const dropProps = (target: string) => ({ 'data-drop-folder': target, onDragOver: (e: React.DragEvent) => { if (e.dataTransfer.types.includes(dragType)) { e.preventDefault(); e.dataTransfer.dropEffect = 'move'; e.currentTarget.classList.add('drag-over'); } }, onDragLeave: (e: React.DragEvent) => e.currentTarget.classList.remove('drag-over'), onDrop: (e: React.DragEvent) => folderDrop(e, target) });
  function clearSearch() { searchGeneration.current++; setSearching(false); setQuery(''); setSearch(''); setCalendarSearch(null); setCalendarResults({ events: [], nextPageTokens: {} }); }
  async function findCalendar(plan: CalendarSearch, more = false, request = ++searchGeneration.current) {
    setSearching(true);
    try { const page = await api.searchEvents({ ...plan, ...(more ? { pageTokens: calendarResults.nextPageTokens } : {}) });
      if (request !== searchGeneration.current) return;
      setCalendarSearch(plan); setCalendarResults(old => ({ ...page, events: more ? [...new Map([...old.events, ...page.events].map(event => [JSON.stringify([event.accountId, event.calendarId, event.id]), event])).values()].sort((a, b) => a.start.localeCompare(b.start)) : page.events }));
    } catch (e) { if (request === searchGeneration.current) error(e); } finally { if (request === searchGeneration.current) setSearching(false); }
  }
  async function runSearch(e: React.FormEvent) {
    e.preventDefault(); if (!search.trim()) { clearSearch(); return; } const request = ++searchGeneration.current; setSearching(true);
    try {
      if (view === 'calendar') { const plan = ai ? await api.calendarSearchQuery(search) : { ...defaultCalendarRange(), query: search.trim() }; if (request !== searchGeneration.current) return; await findCalendar({ ...plan, accountId: accountId || undefined }, false, request); }
      else { const q = ai ? await api.searchQuery(search) : search.trim(); if (request === searchGeneration.current) setQuery(q); }
    } catch (e) { if (request === searchGeneration.current) error(e); } finally { if (request === searchGeneration.current) setSearching(false); }
  }
  const modalOpen = settings || compose || eventDraft || help || folderModal;
  const performCommand = (name: string) => { if (name === 'settings') setSettings(true); if (modalOpen) return; const mail = activeMail || current; if (name === 'compose') newCompose(); if (name === 'event') newEvent(); if (name === 'preview') setPreview(v => !v); if (name === 'theme') setTheme(v => v === 'dark' ? 'light' : 'dark'); if (name === 'mail' || name === 'calendar') setView(name); if (name === 'reply' && mail) newCompose('reply', mail); if (name === 'forward' && mail) newCompose('forward', mail); if (name === 'trash') void mutate({ kind: 'trash' }, messageRef ? [messageRef] : undefined); if (name === 'refresh') { void loadRef.current(); if (calendarSearch) void findCalendar(calendarSearch); else void loadEvents(); } };
  const commandRef = useRef(performCommand); commandRef.current = performCommand;
  useEffect(() => window.desktop?.onCommand(name => commandRef.current(name)), []);
  useEffect(() => { function key(e: KeyboardEvent) { const typing = (e.target as HTMLElement).closest('input,textarea,[contenteditable="true"]'); if (modalOpen) return; if (e.key === 'Escape') { if (viewMenu) { e.preventDefault(); setViewMenu(false); viewMenuRef.current?.querySelector<HTMLButtonElement>('.view-button')?.focus(); return; } setMoveMenu(false); if (messageRef) { if (window.desktop) window.desktop.closeWindow(); else window.close(); } else setSelected([]); }
    if ((e.metaKey || e.ctrlKey) && ['k', 'f'].includes(e.key.toLowerCase())) { e.preventDefault(); searchRef.current?.focus(); }
    if (typing || messageRef) return; if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'a') { e.preventDefault(); setSelected(visible.map(keyOf)); }
    if ((e.key === 'Backspace' || e.key === 'Delete') && selected.length && !busy) { e.preventDefault(); void mutate({ kind: 'trash' }); }
    if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'n') { e.preventDefault(); newCompose(); }
    if (e.key === 'Enter' && current) { e.preventDefault(); openMail(current); }
    if (['ArrowDown', 'ArrowUp'].includes(e.key) && view === 'mail' && visible.length) { e.preventDefault(); const old = visible.findIndex(m => keyOf(m) === (anchor || selected.at(-1))); const i = Math.max(0, Math.min(visible.length - 1, old + (e.key === 'ArrowDown' ? 1 : -1))); const k = keyOf(visible[i]); const s = selectRows(visible.map(keyOf), selected, k, anchor, false, e.shiftKey); setSelected(s.selected); if (!e.shiftKey) setAnchor(k); document.querySelector(`[data-key="${CSS.escape(k)}"]`)?.scrollIntoView({ block: 'nearest' }); }
    if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'z' && toast?.undo) { e.preventDefault(); void undo(); }
  } window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); });
  async function undo() { if (!toast?.undo) return; const entries = toast.undo; setBusy(true); try { await api.undo(entries); setToast({ text: 'Action undone' }); await loadRef.current(); } catch (e) { error(e); } finally { setBusy(false); } }
  const customFolders = [...new Set(folders.filter(f => !accountId || !f.accountId || f.accountId === accountId).map(f => f.name))].sort();
  const account = accounts.find(a => a.id === accountId); const folderName = systemFolders.find(f => f.id === folder)?.name || folder;
  const viewEvents = events.filter(e => !accountId || e.accountId === accountId);
  function resize(e: React.PointerEvent) { e.preventDefault(); const startX = e.clientX, width = paneWidth; e.currentTarget.setPointerCapture(e.pointerId); const move = (event: PointerEvent) => { const value = Math.min(700, Math.max(330, width + startX - event.clientX)); setPaneWidth(value); localStorage.setItem('raizormail-pane-width', String(value)); }; const end = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', end); }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', end); }
  const overlays = <>{dragGhost && <div className="drag-ghost" style={{ left: dragGhost.x + 15, top: dragGhost.y + 14 }}><MailIcon size={15}/>{dragGhost.count} message{dragGhost.count > 1 ? 's' : ''}</div>}{toast && <div className={`toast ${toast.error ? 'error' : ''}`} role={toast.error ? 'alert' : 'status'}>{toast.error ? <AlertCircle size={18}/> : <Check size={18}/>}<span>{toast.text}</span>{toast.undo && <button onClick={undo} disabled={busy}>Undo</button>}<IconButton label="Dismiss notification" onClick={() => setToast(null)}><X size={16}/></IconButton></div>}{compose && <Composer initial={compose} accounts={accounts} api={api} demo={demo} onClose={() => setCompose(null)} onSaved={m => { notify(m); void loadRef.current(); }} onError={error}/>} {eventDraft && <EventEditor initial={eventDraft} calendars={calendars} api={api} demo={demo} onClose={() => setEventDraft(null)} onSaved={m => { notify(m); void loadEvents(); if (calendarSearch) void findCalendar(calendarSearch); }} onError={error}/>} {settings && <Settings accounts={connected} signatureAccounts={accounts} config={config} demo={demo} onClose={() => setSettings(false)} onConnected={reconnect} onConfig={setConfig} onDemo={setDemoMode} onError={error}/>} {folderModal && <Modal title="New folder" onClose={() => setFolderModal(false)}><form onSubmit={async e => { e.preventDefault(); setBusy(true); try { await api.createFolder(newFolder.trim(), accountId || undefined); setFolders(await api.listFolders()); setFolderModal(false); setNewFolder(''); notify('Folder created'); } catch (e) { error(e); } finally { setBusy(false); } }}><div className="form-content"><label>Folder name<input autoFocus value={newFolder} onChange={e => setNewFolder(e.target.value)} required placeholder="e.g. Clients / Acme"/></label><p className="form-hint">{account ? `Created in ${account.email}.` : 'Created in each connected account for use in the unified inbox.'}</p></div><div className="modal-footer"><span className="spacer"/><button className="primary" disabled={busy || !newFolder.trim()}>Create folder</button></div></form></Modal>}{help && <Modal title="A few familiar shortcuts" onClose={() => setHelp(false)}><div className="shortcuts">{[['Click', 'Select without marking read'], ['Double-click / Enter', 'Open message and mark read'], ['⌘ + click', 'Add or remove a selection'], ['Shift + click', 'Select a range'], ['⌘ A', 'Select all loaded messages'], ['Delete', 'Move selection to Trash'], ['⌘ Z', 'Undo the last mail action'], ['⌘ K', 'Search your mail'], ['Esc', 'Close an open message'], ['Drag to Calendar', 'Create an event from an email']].map(([key, desc]) => <div key={key}><kbd>{key}</kbd><span>{desc}</span></div>)}</div></Modal>}</>;
  if (messageRef) return <div className="message-window"><div className="window-titlebar"><span>{demo ? 'Sample message' : 'Message'} · rAIzorMail</span><span className="spacer"/><span className="muted small-text">Esc to close</span></div>{activeMail ? <><div className="popup-toolbar"><button className="secondary" onClick={() => newCompose('reply', activeMail)}><Reply size={16}/>Reply</button><button className="secondary" onClick={() => newCompose('forward', activeMail)}><Forward size={16}/>Forward</button><span className="spacer"/><IconButton label="Delete message" disabled={busy} onClick={() => void mutate({ kind: 'trash' }, [messageRef])}><Trash2 size={18}/></IconButton></div><MailContent mail={activeMail} api={api} onCompose={newCompose} onEvent={m => newEvent(new Date(), m)} onError={error}/></> : <div className="empty-state"><Loader2 className="spin"/><h2>Opening your message…</h2></div>}{overlays}</div>;
  return <div className="app-shell">
    <nav className="app-rail" aria-label="App navigation"><div className="rail-top"><Crest small/></div><button className={view === 'mail' ? 'active' : ''} aria-label="Mail" title="Mail" onClick={() => setView('mail')}><MailIcon size={21}/></button><button className={view === 'calendar' ? 'active' : ''} aria-label="Calendar" title="Calendar — drop an email to create an event" onClick={() => setView('calendar')} data-drop-date={new Date().toISOString()} onDragOver={e => { e.preventDefault(); e.currentTarget.classList.add('drag-over'); }} onDragLeave={e => e.currentTarget.classList.remove('drag-over')} onDrop={e => { e.currentTarget.classList.remove('drag-over'); void calendarDrop(e, new Date()); }}><CalendarDays size={21}/></button><div className="spacer"/><button aria-label="Keyboard shortcuts" title="Keyboard shortcuts" onClick={() => setHelp(true)}><CircleHelp size={20}/></button><button aria-label="Settings" title="Settings" onClick={() => setSettings(true)}><SettingsIcon size={21}/></button><span className="profile-circle">TH</span></nav>
    <aside className="sidebar"><div className="brand"><span>r<span className="brand-ai">AI</span>zor<span className="brand-mail">Mail</span></span><small>by rAIzor crest</small></div><button className="compose-button" onClick={() => newCompose()}><Plus size={19}/>New message<span>⌘ N</span></button>
    <div className="account-picker"><span className="account-stack"><span style={{ background: account?.color || '#c98140' }}/>{!accountId && <span style={{ background: '#94a88b' }}/>}</span><select aria-label="Choose account" value={accountId} onChange={e => setAccountId(e.target.value)}><option value="">All accounts</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select><ChevronDown size={14}/></div>
    {view === 'mail' ? <div className="folder-navigation"><div className="sidebar-label">Mailboxes</div>{systemFolders.map(f => <button key={f.id} className={`folder-button ${folder === f.id && !query ? 'active' : ''}`} onClick={() => { setFolder(f.id); setQuery(''); setSearch(''); }} {...(['INBOX', 'TRASH', 'SPAM'].includes(f.id) ? dropProps(f.id) : {})}><f.icon size={17}/><span>{f.name}</span>{folder === f.id && !query && messages.filter(m => m.unread).length > 0 && <span className="count">{messages.filter(m => m.unread).length}{Object.keys(pageTokens).length ? '+' : ''}</span>}</button>)}<div className="sidebar-label folders-label"><span>Your folders</span><IconButton label="Create folder" onClick={() => setFolderModal(true)}><Plus size={14}/></IconButton></div>{customFolders.map((f, i) => <button className={`folder-button custom-folder ${folder === f && !query ? 'active' : ''}`} key={f} onClick={() => { setFolder(f); setQuery(''); setSearch(''); }} {...dropProps(f)}><Folder size={16} className={`folder-color-${i % 4}`}/><span>{f}</span></button>)}</div> : <><MiniCalendar date={date} onDate={setDate} onDropDate={calendarDrop}/><div className="sidebar-label">Your calendars</div><div className="calendar-list">{calendars.filter(c => !accountId || c.accountId === accountId).map(c => <div key={`${c.accountId}:${c.id}`}><span className="account-dot" style={{ background: c.color }}/>{c.name}</div>)}</div></>}
    <div className="sidebar-bottom">{demo && <button className="demo-connect" onClick={() => setSettings(true)}><span className="demo-dot"/><div><strong>Sample mailbox</strong><span>Connect your Google accounts</span></div><ChevronRight size={15}/></button>}<div className="mountains"><svg viewBox="0 0 240 68" fill="none"><path d="m-10 70 54-49 23 22 40-39 47 51 22-25 66 42" stroke="currentColor" strokeWidth="1.2"/><path d="m66 44 40-40 22 24-19-7-11 10-10-1m66 25 22-25 29 29M9 70l52-28 26 29 53-29 39 29" stroke="currentColor" strokeWidth="1" opacity=".5"/></svg><span>A clearer view of your day.</span></div></div></aside>
    <main className="workspace"><div className="topbar"><form className="search-box" onSubmit={runSearch}><Search size={18}/><select aria-label="Search in" className="search-scope" value={view} onChange={e => setView(e.target.value as 'mail' | 'calendar')}><option value="mail">Mail</option><option value="calendar">Calendar</option></select><input ref={searchRef} value={search} onChange={e => setSearch(e.target.value)} placeholder={view === 'calendar' ? ai ? 'e.g. meetings with Acme next week' : 'Search calendar events…' : ai ? 'e.g. invoices from Acme last month' : 'Search all your mail…'} aria-label={view === 'calendar' ? 'Search calendar events' : 'Search mail'}/>{search && <IconButton label="Clear search" onClick={clearSearch}><X size={15}/></IconButton>}<button type="button" className={`ai-toggle ${ai ? 'active' : ''}`} aria-pressed={ai} title={demo ? 'Try sample natural-language search' : 'Search using Gemini'} onClick={() => setAi(!ai)}><Sparkles size={14}/>AI</button><kbd>⌘ K</kbd>{searching && <Loader2 size={16} className="spin"/>}<button className="sr-only" type="submit">Search</button></form><div className="topbar-actions"><IconButton label={theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'} onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>{theme === 'dark' ? <Sun size={19}/> : <Moon size={19}/>}</IconButton><div className="view-menu-wrap" ref={viewMenuRef}><button aria-expanded={viewMenu} aria-controls="view-options" className={`view-button ${viewMenu ? 'active' : ''}`} onClick={() => setViewMenu(!viewMenu)}><PanelRight size={17}/>View<ChevronDown size={13}/></button>{viewMenu && <><div className="menu-dismiss" onClick={() => setViewMenu(false)}/><div className="dropdown view-dropdown" id="view-options"><div className="dropdown-heading"><strong>Arrange your workspace</strong><IconButton label="Close View menu" onClick={() => setViewMenu(false)}><X size={15}/></IconButton></div><button onClick={() => setPreview(!preview)}><PanelRight size={16}/>Reading pane<span className={`toggle ${preview ? 'on' : ''}`}/></button><button onClick={() => setAgenda(!agenda)}><CalendarDays size={16}/>My day<span className={`toggle ${agenda ? 'on' : ''}`}/></button><button onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}><Moon size={16}/>Dark appearance<span className={`toggle ${theme === 'dark' ? 'on' : ''}`}/></button><p>Inline previews are always on.<br/>Only opening a message marks it read.</p></div></>}</div></div></div>
    <div className="view-heading"><div className="heading-title"><h1>{view === 'calendar' ? 'Calendar' : query ? 'Search results' : folder === 'INBOX' && !accountId ? 'Unified inbox' : folderName}</h1><span>{view === 'calendar' ? date.toLocaleDateString(undefined, { month: 'long', year: 'numeric' }) : account?.email || `${accounts.length} accounts, one clear view`}</span></div><div className="heading-meta">{demo && <span className="demo-badge">Demo</span>}<IconButton label="Refresh mail and calendar" disabled={loading || searching} onClick={() => { void loadRef.current(); if (calendarSearch) void findCalendar(calendarSearch); else void loadEvents(); }}><RefreshCw size={17} className={loading ? 'spin' : ''}/></IconButton></div></div>
    {view === 'calendar' ? calendarSearch ? <CalendarSearchResults search={calendarSearch} results={calendarResults} calendars={calendars} busy={searching} onMore={() => void findCalendar(calendarSearch, true)} onClear={clearSearch} onEdit={setEventDraft}/> : <CalendarView date={date} events={viewEvents} onDate={setDate} onNew={d => newEvent(d)} onEdit={setEventDraft} onDrop={calendarDrop}/> : <>
    {query ? <div className="search-summary"><Search size={15}/><span>{ai && demo ? 'Demo interpretation: ' : 'Search: '}<code>{query}</code></span><button onClick={() => { setQuery(''); setSearch(''); }}>Clear</button></div> : folder === 'INBOX' && <div className="category-bar">{([{ id: 'primary', name: 'Primary', icon: Inbox }, { id: 'promotions', name: 'Promotions', icon: Tag }, { id: 'social', name: 'Social', icon: Users }] as const).map(c => <button className={category === c.id ? 'active' : ''} key={c.id} onClick={() => setCategory(c.id)} {...dropProps(categoryLabel[c.id])}><c.icon size={17}/>{c.name}{category === c.id && messages.filter(m => m.unread).length > 0 && <span>{messages.filter(m => m.unread).length}</span>}</button>)}</div>}
    <div className="mail-toolbar"><div className="selection-label">{selected.length ? <><strong>{selected.length}</strong> selected<IconButton label="Clear selection" onClick={() => setSelected([])}><X size={14}/></IconButton></> : <button className={unreadOnly ? 'filter-toggle active' : 'filter-toggle'} onClick={() => setUnreadOnly(!unreadOnly)}>{unreadOnly ? 'Unread mail' : 'All messages'}<ChevronDown size={13}/></button>}</div><div className="toolbar-divider"/><IconButton label="Delete selected messages" disabled={!selected.length || busy} onClick={() => void mutate({ kind: 'trash' })}><Trash2 size={17}/></IconButton><IconButton label="Archive selected messages" disabled={!selected.length || busy} onClick={() => void mutate({ kind: 'archive' })}><Archive size={17}/></IconButton><div className="move-menu-wrap"><IconButton label="Move selected messages" disabled={!selected.length || busy} onClick={() => setMoveMenu(!moveMenu)}><Folder size={17}/></IconButton>{moveMenu && <><div className="menu-dismiss" onClick={() => setMoveMenu(false)}/><div className="dropdown move-dropdown"><strong>Move to folder</strong>{['INBOX', ...customFolders, 'TRASH'].map(f => <button key={f} onClick={() => { setMoveMenu(false); void mutate(f === 'TRASH' ? { kind: 'trash' } : { kind: 'move', target: f, source: query ? 'SEARCH' : folder }); }}><Folder size={15}/>{f === 'INBOX' ? 'Inbox' : f === 'TRASH' ? 'Trash' : f}</button>)}</div></>}</div><IconButton label="Mark selected messages unread" disabled={!selected.length || busy} onClick={() => void mutate({ kind: 'read', value: false })}><MailIcon size={17}/></IconButton>{current && <IconButton label="Reply to selected email" onClick={() => newCompose('reply', current)}><Reply size={17}/></IconButton>}<span className="spacer"/>{busy && <Loader2 size={16} className="spin"/>}<span className="message-count">{visible.length}{Object.keys(pageTokens).length ? '+' : ''} messages</span><span className="sort-label">Newest first<ArrowDown size={13}/></span></div>
    {!!warnings.length && <div className="warning-banner" role="alert"><AlertCircle size={16}/><span>{warnings.join(' ')}</span><button onClick={() => void loadRef.current()}>Retry</button></div>}
    <div className={`mail-workspace ${preview ? 'has-reading-pane' : ''}`}><section className="message-list" aria-label="Email list"><div className="list-column-head"><span>From</span><span>Subject & preview</span><span>Received</span></div><div className="mail-rows" role="listbox" aria-label="Messages" aria-multiselectable="true">
    {loading && !messages.length ? <div className="empty-state"><Loader2 className="spin" size={25}/><h2>Gathering your mail…</h2></div> : !visible.length ? <div className="empty-state"><Inbox size={38}/><h2>{query ? 'No matching messages' : unreadOnly ? 'All caught up' : 'A little breathing room'}</h2><p>{query ? 'Try another sender, keyword, or date range.' : unreadOnly ? 'There are no unread messages in this view.' : 'No messages in this folder yet.'}</p>{query && <button className="secondary" onClick={() => { setQuery(''); setSearch(''); }}>Back to inbox</button>}</div> : visible.map((m, i) => { const a = accounts.find(a => a.id === m.accountId); const previous = visible[i - 1]; const day = localDate(new Date(m.date)); const group = day === localDate(new Date()) ? 'Today' : day === localDate(addDays(new Date(), -1)) ? 'Yesterday' : new Date(m.date).toLocaleDateString(undefined, { month: 'long', day: 'numeric' }); return <div key={keyOf(m)}>{(!previous || day !== localDate(new Date(previous.date))) && <div className="date-separator">{group}<span/></div>}<div role="option" aria-selected={selected.includes(keyOf(m))} aria-label={`${m.unread ? 'Unread: ' : ''}${m.from}: ${m.subject}`} tabIndex={selected.includes(keyOf(m)) || i === 0 ? 0 : -1} data-key={keyOf(m)} className={`mail-row ${m.unread ? 'unread' : ''} ${selected.includes(keyOf(m)) ? 'selected' : ''}`} onClick={e => select(m, e)} onDoubleClick={() => { if (Date.now() >= suppressClick.current) openMail(m); }} onPointerDown={e => pointerDrag(e, m)} onDragStart={e => e.preventDefault()}><span className={`unread-dot ${m.unread ? 'is-unread' : ''}`}/><div className="row-sender"><span className="avatar" style={{ '--avatar-color': a?.color } as React.CSSProperties}>{initials(m.from)}</span><div><strong>{m.from}</strong><small><span className="account-dot" style={{ background: a?.color }}/>{a?.name}</small></div></div><div className="row-content"><div className="row-subject"><strong>{m.subject}</strong>{m.attachments.length > 0 && <Paperclip size={14}/>}</div><p>{m.snippet.replace(/&#39;/g, "'").replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&lt;/g, '<').replace(/&gt;/g, '>')}</p></div><div className="row-meta"><time>{day === localDate(new Date()) ? new Date(m.date).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' }) : new Date(m.date).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</time><button className={`star-button ${m.starred ? 'starred' : ''}`} title={m.starred ? 'Remove star' : 'Star message'} aria-label={`${m.starred ? 'Unstar' : 'Star'} ${m.subject}`} onDoubleClick={e => e.stopPropagation()} onClick={e => { e.stopPropagation(); void mutate({ kind: 'star', value: !m.starred }, [{ id: m.id, accountId: m.accountId }], true); }}><Star size={15} fill={m.starred ? 'currentColor' : 'none'}/></button></div></div></div>; })}
    {!!Object.keys(pageTokens).length && <button className="load-more secondary" disabled={loading} onClick={() => void load(true)}>{loading ? 'Loading…' : 'Load more messages'}</button>}</div><footer className="list-footer"><span className="sync-dot"/>{demo ? 'Sample mailbox' : warnings.length ? 'Some accounts need attention' : syncTime ? `Synced ${syncTime.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}` : 'Connecting…'}<span className="spacer"/><span>⌘ click to select multiple</span></footer></section>
    {preview ? <><div className="pane-resizer" role="separator" aria-label="Resize reading pane" aria-orientation="vertical" tabIndex={0} onPointerDown={resize} onKeyDown={e => { if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') { e.preventDefault(); const w = Math.min(700, Math.max(330, paneWidth + (e.key === 'ArrowLeft' ? 20 : -20))); setPaneWidth(w); localStorage.setItem('raizormail-pane-width', String(w)); } }}/><section className="reading-pane" style={{ width: paneWidth }}>{current ? <MailContent mail={current} api={api} onCompose={newCompose} onEvent={m => newEvent(new Date(), m)} onOpen={() => openMail(current)} onError={error} compact/> : <div className="empty-state"><MailOpen size={34}/><h2>{selected.length > 1 ? `${selected.length} messages selected` : 'A closer look'}</h2><p>{selected.length > 1 ? 'Move, archive, or delete them together.' : 'Select a message to preview it here.\nIt stays unread until you open it.'}</p></div>}</section></> : agenda && <Agenda events={viewEvents} date={date} onCalendar={() => setView('calendar')} onEvent={setEventDraft} onNew={() => newEvent()} onDrop={calendarDrop}/>}
    </div></>}
    </main>{overlays}
  </div>;
}
