import { useEffect, useRef } from 'react';
import { Plus, ChevronLeft, ChevronRight, CalendarDays, ArrowUpRight } from 'lucide-react';
import type { CalendarEvent } from './types';
import { addDays, localDate, weekStart } from './domain';
import { IconButton } from './components';
export function CalendarView({ date, events, onDate, onNew, onEdit, onDrop }: { date: Date; events: CalendarEvent[]; onDate: (d: Date) => void; onNew: (d: Date) => void; onEdit: (e: CalendarEvent) => void; onDrop: (e: React.DragEvent, d: Date) => void }) {
  const start = weekStart(date); const days = Array.from({ length: 7 }, (_, i) => addDays(start, i)); const scroll = useRef<HTMLDivElement>(null);
  useEffect(() => { if (scroll.current) scroll.current.scrollTop = 8 * 64 - 20; }, []);
  return <div className="calendar-view"><div className="calendar-toolbar"><button className="secondary" onClick={() => onDate(new Date())}>Today</button><IconButton label="Previous week" onClick={() => onDate(addDays(date, -7))}><ChevronLeft size={18}/></IconButton><IconButton label="Next week" onClick={() => onDate(addDays(date, 7))}><ChevronRight size={18}/></IconButton><span>{start.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })} – {days[6].toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}</span><span className="spacer"/><span className="muted small-text">Week view</span><button className="primary" onClick={() => onNew(date)}><Plus size={16}/>New event</button></div>
    <div className="week-heading"><div className="timezone">{Intl.DateTimeFormat().resolvedOptions().timeZone.split('/').pop()?.replaceAll('_', ' ')}</div>{days.map(d => <div key={localDate(d)} className={localDate(d) === localDate(new Date()) ? 'current-day' : ''}><span>{d.toLocaleDateString(undefined, { weekday: 'short' })}</span><button onClick={() => onNew(d)}>{d.getDate()}</button></div>)}</div>
    <div className="all-day-grid"><small>All day</small>{days.map(d => <div key={localDate(d)} data-drop-date={d.toISOString()} onDragOver={e => e.preventDefault()} onDrop={e => onDrop(e, d)}>{events.filter(e => e.allDay && e.start.slice(0, 10) <= localDate(d) && e.end.slice(0, 10) > localDate(d)).map(e => <button key={`${e.accountId}:${e.id}`} onClick={() => onEdit(e)} style={{ borderColor: e.color }}>{e.title}</button>)}</div>)}</div>
    <div className="week-scroll" ref={scroll}><div className="week-grid"><div className="time-gutter">{Array.from({ length: 24 }, (_, h) => <span key={h} style={{ top: h * 64 }}>{h === 0 ? '' : `${h % 12 || 12} ${h < 12 ? 'AM' : 'PM'}`}</span>)}</div>{days.map(d => {
      const dayEvents = events.filter(e => !e.allDay && localDate(new Date(e.start)) === localDate(d));
      return <div className="day-column" key={localDate(d)}>{Array.from({ length: 24 }, (_, h) => { const slot = new Date(d); slot.setHours(h); return <button className="hour-slot" key={h} data-drop-date={slot.toISOString()} aria-label={`New event ${d.toDateString()} at ${h}:00`} onClick={() => onNew(slot)} onDragOver={e => { e.preventDefault(); e.currentTarget.classList.add('drag-over'); }} onDragLeave={e => e.currentTarget.classList.remove('drag-over')} onDrop={e => { e.currentTarget.classList.remove('drag-over'); onDrop(e, slot); }}/>; })}{dayEvents.map(e => { const s = new Date(e.start); const end = new Date(e.end); const overlaps = dayEvents.filter(x => x.start < e.end && x.end > e.start).sort((a, b) => a.start.localeCompare(b.start) || a.id.localeCompare(b.id)); const column = overlaps.findIndex(x => x.id === e.id && x.accountId === e.accountId); const count = overlaps.length; return <button className="calendar-event" key={`${e.accountId}:${e.id}`} style={{ top: (s.getHours() + s.getMinutes() / 60) * 64, height: Math.max(28, Math.min((end.getTime() - s.getTime()) / 3600000, 24 - s.getHours() - s.getMinutes() / 60) * 64 - 3), left: `calc(${column / count * 100}% + 3px)`, width: `calc(${100 / count}% - 6px)`, '--event-color': e.color || '#94a88b' } as React.CSSProperties} onClick={() => onEdit(e)}><strong>{e.title}</strong><span>{s.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}</span>{e.location && <small>{e.location}</small>}</button>; })}</div>;
    })}</div></div></div>;
}
export function Agenda({ events, date, onCalendar, onEvent, onNew, onDrop }: { events: CalendarEvent[]; date: Date; onCalendar: () => void; onEvent: (e: CalendarEvent) => void; onNew: () => void; onDrop: (e: React.DragEvent, date: Date) => void }) {
  const today = events.filter(e => e.allDay ? e.start <= localDate(date) && e.end > localDate(date) : localDate(new Date(e.start)) === localDate(date)).sort((a, b) => a.start.localeCompare(b.start));
  return <aside className="agenda" data-drop-date={date.toISOString()} onDragOver={e => { e.preventDefault(); e.currentTarget.classList.add('drag-over'); }} onDragLeave={e => { if (!e.currentTarget.contains(e.relatedTarget as Node)) e.currentTarget.classList.remove('drag-over'); }} onDrop={e => { e.currentTarget.classList.remove('drag-over'); onDrop(e, date); }}><div className="agenda-heading"><span>My day</span><IconButton label="Open calendar" onClick={onCalendar}><ArrowUpRight size={17}/></IconButton></div><div className="agenda-date"><span>{date.toLocaleDateString(undefined, { weekday: 'long' })}</span><strong>{date.getDate()}</strong><span>{date.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</span></div><div className="agenda-section"><span>On your calendar</span><IconButton label="Add an event" onClick={onNew}><Plus size={16}/></IconButton></div>{today.length ? <div className="agenda-events">{today.map(e => <button key={`${e.accountId}:${e.id}`} className="agenda-event" onClick={() => onEvent(e)}><div className="event-line" style={{ background: e.color }}/><div><small>{e.allDay ? 'All day' : new Date(e.start).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}</small><strong>{e.title}</strong>{e.location && <span>{e.location}</span>}</div></button>)}</div> : <p className="agenda-empty">A little room to breathe.<br/>No events for this day.</p>}<div className="calendar-drop"><CalendarDays size={25}/><strong>From inbox to calendar</strong><p>Drag an email here to turn it into an appointment.</p></div><div className="agenda-footer">Make space for what matters.</div></aside>;
}
