import { useEffect, useRef, useState } from 'react';
import DOMPurify from 'dompurify';
import { X, Paperclip, Send, Trash2, ChevronLeft, ChevronRight, ArrowUpRight, Reply, ReplyAll, Forward, Download, CalendarDays, Loader2, Plus, Check, ExternalLink } from 'lucide-react';
import type { Account, Calendar, CalendarEvent, Compose, Config, Mail, MailAPI, Signature } from './types';
import { readAttachments } from './attachments';
import { composeChanged, initialSignature, replaceSignature, signatureBlock } from './compose';
import { WritingAssistant } from './WritingAssistant';
import { SignatureSettings } from './SignatureSettings';
import { getAPI } from './api';
import { addDays, initials, localDate, localDateTime } from './domain';
export function Crest({ small = false }: { small?: boolean }) { return <svg className={small ? 'crest small' : 'crest'} viewBox="0 0 48 40" fill="none" aria-hidden="true"><path d="M3 33 18 8l8 14 6-9 13 20H3Z" stroke="currentColor" strokeWidth="2.4" strokeLinejoin="round"/><path d="m11 20 7-12 8 14-7-4-4 5-4-3ZM26 22l6-9 7 11-7-4-6 2Z" fill="currentColor" opacity=".3"/><path d="M7 38h34" stroke="currentColor" strokeWidth="2"/></svg>; }
export function IconButton({ children, label, onClick, disabled, className = '' }: { children: React.ReactNode; label: string; onClick?: () => void; disabled?: boolean; className?: string }) { return <button type="button" className={`icon-button ${className}`} title={label} aria-label={label} onClick={onClick} disabled={disabled}>{children}</button>; }
export function Modal({ title, children, onClose, className = '' }: { title: string; children: React.ReactNode; onClose: () => void; className?: string }) {
  const ref = useRef<HTMLDivElement>(null); const closeRef = useRef(onClose); closeRef.current = onClose;
  useEffect(() => { const old = document.activeElement as HTMLElement; const node = ref.current; node?.focus(); function key(e: KeyboardEvent) { if (e.key === 'Escape') { e.stopPropagation(); closeRef.current(); } if (e.key === 'Tab') { const focusable = Array.from(node?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]') || []).filter(el => el.offsetParent !== null); const first = focusable[0], last = focusable.at(-1); if (e.shiftKey && (document.activeElement === first || document.activeElement === node)) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } } } node?.addEventListener('keydown', key); return () => { node?.removeEventListener('keydown', key); old?.focus(); }; }, []);
  return <div className="modal-backdrop"><div className={`modal ${className}`} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={ref}><div className="modal-heading"><h2>{title}</h2><IconButton label="Close dialog" onClick={onClose}><X size={19}/></IconButton></div>{children}</div></div>;
}
export function MailContent({ mail, api, onCompose, onEvent, onOpen, onError, compact = false }: { mail: Mail; api: MailAPI; onCompose: (kind: 'reply' | 'replyAll' | 'forward', m: Mail) => void; onEvent: (m: Mail) => void; onOpen?: () => void; onError: (e: unknown) => void; compact?: boolean }) {
  const [showHtml, setShowHtml] = useState(true);
  const [showImages, setShowImages] = useState(true);
  const clean = mail.html ? DOMPurify.sanitize(mail.html, { FORBID_TAGS: ['script', 'form', 'input', 'button', 'iframe', 'object', 'embed', 'link', 'meta', 'base', 'svg', 'math', 'video', 'audio'], FORBID_ATTR: ['srcset', 'action', 'formaction', 'background'] }) : '';
  const html = `<!doctype html><html><head><meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data: ${showImages ? 'https: http:' : ''}; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><style>body{font:15px/1.65 Arial,sans-serif;color:#24251f;background:#fff;padding:12px;overflow-wrap:anywhere}img{max-width:100%}a{color:#a05c27}table{max-width:100%}</style></head><body>${clean}</body></html>`;
  return <article className={`mail-content ${compact ? 'compact' : ''}`}>
    <div className="reading-actions"><div><IconButton label="Reply" onClick={() => onCompose('reply', mail)}><Reply size={17}/></IconButton><IconButton label="Reply all" onClick={() => onCompose('replyAll', mail)}><ReplyAll size={17}/></IconButton><IconButton label="Forward" onClick={() => onCompose('forward', mail)}><Forward size={17}/></IconButton></div><div><IconButton label="Create calendar event" onClick={() => onEvent(mail)}><CalendarDays size={17}/></IconButton>{onOpen && <IconButton label="Open in separate window" onClick={onOpen}><ArrowUpRight size={18}/></IconButton>}</div></div>
    <div className="message-heading"><h2>{mail.subject}</h2><div className="sender-block"><span className="avatar large">{initials(mail.from)}</span><div><strong>{mail.from}</strong><span>{mail.fromEmail}</span><small>To: {mail.to}{mail.cc ? ` · Cc: ${mail.cc}` : ''}</small></div></div><div className="message-date">{new Date(mail.date).toLocaleString(undefined, { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' })}{mail.unread && <span className="unread-note">Preview · still unread</span>}</div></div>
    {mail.attachments.length > 0 && <div className="attachments">{mail.attachments.map(a => <button key={a.id} onClick={() => api.attachment({ id: mail.id, accountId: mail.accountId }, a).catch(onError)}><Paperclip size={15}/><span>{a.name}<small>{a.size > 1024 ? `${Math.round(a.size / 1024)} KB` : `${a.size} B`}</small></span><Download size={15}/></button>)}</div>}
    {mail.html && <div className="html-notice"><button onClick={() => setShowImages(v => !v)}>{showImages ? 'Hide remote images' : 'Show remote images'}</button><button onClick={() => setShowHtml(v => !v)}>{showHtml ? 'Plain text' : 'Formatted email'}</button></div>}
    {mail.html && showHtml ? <iframe className="email-frame" title="Email content" sandbox="allow-popups allow-popups-to-escape-sandbox" srcDoc={html}/> : <div className="message-body">{mail.text || mail.snippet}</div>}
    <div className="message-bottom"><button className="secondary" onClick={() => onCompose('reply', mail)}><Reply size={16}/>Reply</button><button className="secondary" onClick={() => onCompose('forward', mail)}><Forward size={16}/>Forward</button></div>
  </article>;
}
export function Composer({ initial, accounts, api, demo, onClose, onSaved, onError }: { initial: Compose; accounts: Account[]; api: MailAPI; demo: boolean; onClose: () => void; onSaved: (message: string) => void; onError: (e: unknown) => void }) {
  const [c, setC] = useState(initial); const [busy, setBusy] = useState(false); const [more, setMore] = useState(!!initial.cc || !!initial.bcc); const fileInput = useRef<HTMLInputElement>(null);
  const [attaching, setAttaching] = useState(false); const attachingRef = useRef(false);
  const [draggingFiles, setDraggingFiles] = useState(false); const dragDepth = useRef(0);
  useEffect(() => { const reset = () => { dragDepth.current = 0; setDraggingFiles(false); }; window.addEventListener('dragend', reset); window.addEventListener('drop', reset); return () => { window.removeEventListener('dragend', reset); window.removeEventListener('drop', reset); }; }, []);
  const [writingHelp, setWritingHelp] = useState(false);
  const [confirmClose, setConfirmClose] = useState(false); const [signatureReady, setSignatureReady] = useState(false);
  const [signatures, setSignatures] = useState<Record<string, Signature>>({}); const baseline = useRef(initial); const insertedSignature = useRef(''); const nativeClose = useRef(false);
  useEffect(() => { let alive = true; api.getSignatures().then(data => {
    if (!alive) return; setSignatures(data); const block = initialSignature(initial, data[initial.accountId]); insertedSignature.current = block;
    const prepared = { ...initial, text: replaceSignature(initial.text, '', block) }; baseline.current = prepared; setC(prepared);
  }).catch(onError).finally(() => { if (alive) setSignatureReady(true); }); return () => { alive = false; }; }, [api, initial, onError]);
  function cancelClose() { setConfirmClose(false); if (nativeClose.current) { nativeClose.current = false; window.desktop?.resolveClose(false); } }
  function finishClose() { onClose(); if (nativeClose.current) { nativeClose.current = false; window.desktop?.resolveClose(true); } }
  function requestClose() {
    if (busy || attachingRef.current || !signatureReady) { if (nativeClose.current) { nativeClose.current = false; window.desktop?.resolveClose(false); } return; }
    if (composeChanged(baseline.current, c)) setConfirmClose(true); else finishClose();
  }
  const closeRequest = useRef(requestClose); closeRequest.current = requestClose;
  useEffect(() => { window.desktop?.setCloseGuard(true); const unsubscribe = window.desktop?.onRequestClose(() => { nativeClose.current = true; closeRequest.current(); }); return () => { unsubscribe?.(); window.desktop?.setCloseGuard(false); }; }, []);
  useEffect(() => { if (window.desktop || !composeChanged(baseline.current, c)) return; const guard = (e: BeforeUnloadEvent) => { e.preventDefault(); e.returnValue = ''; }; window.addEventListener('beforeunload', guard); return () => window.removeEventListener('beforeunload', guard); }, [c]);
  const change = (key: keyof Compose, value: unknown) => setC(p => ({ ...p, [key]: value }));
  function changeAccount(id: string) {
    const block = initialSignature({ ...c, accountId: id }, signatures[id]);
    const text = replaceSignature(c.text, insertedSignature.current, block);
    insertedSignature.current = block && text.includes(block) ? block : ''; setC(p => ({ ...p, accountId: id, text }));
  }
  function insertSignature() {
    const block = signatureBlock(signatures[c.accountId]); if (!block) return;
    setC(p => ({ ...p, text: replaceSignature(p.text, '', block) })); insertedSignature.current = block;
  }
  async function save(close: boolean) { if (busy || attachingRef.current || !signatureReady) return; if (!c.to && !c.subject && !c.text && !c.attachments.length) { finishClose(); return; } setBusy(true); try { const d = await api.saveDraft(c); setC(p => ({ ...p, draftId: d.id })); onSaved(demo ? 'Draft saved in the demo mailbox' : 'Draft saved to Gmail'); if (close) finishClose(); } catch (e) { onError(e); } finally { setBusy(false); } }
  async function send(e: React.FormEvent) { e.preventDefault(); if (busy || attachingRef.current || !signatureReady || !c.to.trim()) return; setBusy(true); try { await api.send(c); onSaved(demo ? 'Message added to demo Sent. No email was sent.' : 'Message sent'); onClose(); } catch (e) { onError(e); } finally { setBusy(false); } }
  async function attach(files: File[]) {
    if (!files.length || busy || attachingRef.current || !signatureReady) return;
    attachingRef.current = true; setAttaching(true);
    try { const attachments = await readAttachments(files, c.attachments.reduce((n, f) => n + f.size, 0)); setC(p => ({ ...p, attachments: [...p.attachments, ...attachments] })); }
    catch (e) { onError(e); } finally { attachingRef.current = false; setAttaching(false); }
  }
  function fileDrag(e: React.DragEvent) { return e.dataTransfer.types.includes('Files'); }
  function dropFiles(e: React.DragEvent) {
    if (!fileDrag(e)) return;
    e.preventDefault(); e.stopPropagation(); dragDepth.current = 0; setDraggingFiles(false);
    if (busy || attachingRef.current) return;
    if ([...e.dataTransfer.items].some(item => item.webkitGetAsEntry?.()?.isDirectory)) { onError(new Error('Zip folders before attaching them. You can drop multiple files together.')); return; }
    void attach([...e.dataTransfer.files]);
  }
  if (confirmClose) return <Modal title="Keep this message?" className="draft-decision" onClose={() => { if (!busy) cancelClose(); }}>
    <div className="form-content"><p>{c.draftId ? 'Save your changes to the draft, or discard these edits and keep the previously saved draft.' : 'Save this unfinished message in Drafts, or discard it.'}</p></div>
    <div className="modal-footer"><button type="button" className="text-button danger" disabled={busy} onClick={finishClose}>{c.draftId ? 'Discard changes' : 'Discard'}</button><span className="spacer"/><button type="button" className="secondary" autoFocus disabled={busy} onClick={cancelClose}>Keep editing</button><button type="button" className="primary" disabled={busy} onClick={() => void save(true)}>{busy && <Loader2 size={16} className="spin"/>}Save draft</button></div>
  </Modal>;
  return <Modal title={c.draftId ? 'Continue draft' : 'New message'} className="composer" onClose={requestClose}><form onSubmit={send} className={draggingFiles ? 'file-drag-over' : ''}
    onDragEnter={e => { if (fileDrag(e)) { e.preventDefault(); dragDepth.current++; if (!busy && !attachingRef.current) setDraggingFiles(true); } }}
    onDragOver={e => { if (fileDrag(e)) { e.preventDefault(); e.dataTransfer.dropEffect = busy || attachingRef.current ? 'none' : 'copy'; } }}
    onDragLeave={e => { if (fileDrag(e)) { dragDepth.current = Math.max(0, dragDepth.current - 1); if (!dragDepth.current) setDraggingFiles(false); } }} onDrop={dropFiles}>
    {draggingFiles && <div className="attachment-drop-overlay"><Paperclip size={30}/><strong>Drop files to attach</strong><span>Up to 18 MB per message</span></div>}
    {demo && <div className="form-hint demo-hint">Sample mailbox — messages stay in this demo.</div>}
    <div className="compose-field"><label htmlFor="compose-from">From</label><select id="compose-from" value={c.accountId} disabled={!!c.threadId || !!c.draftId || busy || !signatureReady} onChange={e => changeAccount(e.target.value)}>{accounts.map(a => <option value={a.id} key={a.id}>{a.name} &lt;{a.email}&gt;</option>)}</select></div>
    <div className="compose-field"><label htmlFor="compose-to">To</label><input id="compose-to" disabled={!signatureReady || busy} required value={c.to} onChange={e => change('to', e.target.value)} placeholder="Name or email address"/><button type="button" className="text-button" onClick={() => setMore(!more)}>Cc / Bcc</button></div>
    {more && <><div className="compose-field"><label htmlFor="compose-cc">Cc</label><input id="compose-cc" disabled={!signatureReady || busy} value={c.cc} onChange={e => change('cc', e.target.value)}/></div><div className="compose-field"><label htmlFor="compose-bcc">Bcc</label><input id="compose-bcc" disabled={!signatureReady || busy} value={c.bcc} onChange={e => change('bcc', e.target.value)}/></div></>}
    <div className="compose-field"><label htmlFor="compose-subject">Subject</label><input id="compose-subject" disabled={!signatureReady || busy} value={c.subject} onChange={e => change('subject', e.target.value)} placeholder="Add a subject"/></div>
    {writingHelp && <WritingAssistant draft={c} api={api} demo={demo} onApply={result => { if (!busy) setC(p => ({ ...p, ...result })); }} onClose={() => setWritingHelp(false)} onError={onError}/>}
    <textarea className="compose-body" disabled={!signatureReady || busy} aria-label="Message body" value={c.text} onChange={e => change('text', e.target.value)} placeholder="Write your message…"/>
    {!!c.attachments.length && <div className="compose-attachments">{c.attachments.map(a => <span key={a.id}><Paperclip size={14}/>{a.name}<IconButton label={`Remove ${a.name}`} disabled={busy || attaching || !signatureReady} onClick={() => change('attachments', c.attachments.filter(x => x.id !== a.id))}><X size={13}/></IconButton></span>)}</div>}
    <div className="attachment-hint" role="status">{!signatureReady ? 'Loading your signature…' : attaching ? 'Adding attachments…' : 'Drag files into this message, or use the paperclip.'}</div>
    <footer className="modal-footer"><button type="submit" className="primary" disabled={busy || attaching || !signatureReady || !c.to.trim()}>{busy ? <Loader2 className="spin" size={16}/> : <Send size={16}/>}Send{demo ? ' in demo' : ''}</button><IconButton label="Attach files" onClick={() => fileInput.current?.click()} disabled={busy || attaching || !signatureReady}><Paperclip size={19}/></IconButton><input ref={fileInput} type="file" multiple hidden onChange={e => { void attach([...(e.target.files || [])]); e.target.value = ''; }}/><button type="button" className="text-button" disabled={busy || !signatureReady} onClick={() => setWritingHelp(v => !v)}>AI writing</button><button type="button" className="text-button" disabled={busy || !signatureReady || !signatures[c.accountId]?.text.trim()} onClick={insertSignature}>Insert signature</button><span className="spacer"/><button type="button" className="secondary" disabled={busy || attaching || !signatureReady} onClick={() => { void save(true); }}>Save & close</button></footer>
  </form></Modal>;
}
export function MiniCalendar({ date, onDate, onDropDate }: { date: Date; onDate: (d: Date) => void; onDropDate?: (e: React.DragEvent, d: Date) => void }) {
  const [month, setMonth] = useState(new Date(date.getFullYear(), date.getMonth(), 1));
  useEffect(() => setMonth(new Date(date.getFullYear(), date.getMonth(), 1)), [date.getMonth(), date.getFullYear()]);
  const first = new Date(month); first.setDate(1 - (first.getDay() + 6) % 7);
  return <div className="mini-calendar"><div className="mini-heading"><strong>{month.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</strong><IconButton label="Previous month" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}><ChevronLeft size={14}/></IconButton><IconButton label="Next month" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}><ChevronRight size={14}/></IconButton></div><div className="mini-grid">{['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((d, i) => <span className="weekday" key={i}>{d}</span>)}{Array.from({ length: 42 }, (_, i) => { const d = addDays(first, i); return <button key={i} data-drop-date={d.toISOString()} title={d.toDateString()} aria-label={d.toDateString()} className={`${d.getMonth() !== month.getMonth() ? 'muted' : ''} ${localDate(d) === localDate(new Date()) ? 'today' : ''} ${localDate(d) === localDate(date) ? 'selected-date' : ''}`} onClick={() => onDate(d)} onDragOver={e => { e.preventDefault(); e.currentTarget.classList.add('drag-over'); }} onDragLeave={e => e.currentTarget.classList.remove('drag-over')} onDrop={e => { e.preventDefault(); e.currentTarget.classList.remove('drag-over'); onDropDate?.(e, d); }}>{d.getDate()}</button>; })}</div></div>;
}
export function EventEditor({ initial, calendars, api, demo, onClose, onSaved, onError }: { initial: CalendarEvent; calendars: Calendar[]; api: MailAPI; demo: boolean; onClose: () => void; onSaved: (message: string) => void; onError: (e: unknown) => void }) {
  const [event, setEvent] = useState(initial); const [busy, setBusy] = useState(false); const [confirmDelete, setConfirmDelete] = useState(false);
  const readOnly = !calendars.some(c => c.id === event.calendarId && c.accountId === event.accountId && c.writable) || !!event.attendees?.length;
  const field = (key: keyof CalendarEvent, value: unknown) => setEvent(p => ({ ...p, [key]: value }));
  const display = (s: string) => event.allDay ? s.slice(0, 10) : localDateTime(new Date(s));
  async function save(e: React.FormEvent) { e.preventDefault(); if (readOnly) return; if (+new Date(event.end) <= +new Date(event.start)) { onError(new Error('The end time must be after the start time.')); return; } setBusy(true); try { await api.saveEvent(event); onSaved(demo ? 'Event saved in the demo calendar' : 'Event saved to Google Calendar'); onClose(); } catch (e) { onError(e); } finally { setBusy(false); } }
  return <Modal title={event.id ? 'Event details' : 'New event'} className="event-editor" onClose={() => { if (!busy) onClose(); }}><form onSubmit={save}>
    <div className="form-content">{demo && <p className="form-hint demo-hint">Sample calendar — no invitations will be sent.</p>}{event.attendees?.length ? <p className="form-hint">This is a meeting with guests. Edit it in Google Calendar to manage invitations.</p> : <p className="form-hint">A personal appointment on your calendar. No guests are added.</p>}
    <label>Title<input required value={event.title} disabled={readOnly} onChange={e => field('title', e.target.value)} placeholder="What’s on the calendar?"/></label>
    <label>Calendar<select value={`${event.accountId}|${event.calendarId}`} disabled={!!event.id} onChange={e => { const c = calendars.find(c => `${c.accountId}|${c.id}` === e.target.value)!; setEvent(p => ({ ...p, accountId: c.accountId, calendarId: c.id, color: c.color })); }}>{calendars.filter(c => c.writable || c.id === event.calendarId).map(c => <option key={`${c.accountId}|${c.id}`} value={`${c.accountId}|${c.id}`}>{c.name}</option>)}</select></label>
    <div className="form-pair"><label>Starts<input type={event.allDay ? 'date' : 'datetime-local'} required value={display(event.start)} disabled={readOnly} onChange={e => { if (e.target.value) field('start', event.allDay ? e.target.value : new Date(e.target.value).toISOString()); }}/></label><label>Ends<input type={event.allDay ? 'date' : 'datetime-local'} required value={display(event.end)} disabled={readOnly} onChange={e => { if (e.target.value) field('end', event.allDay ? e.target.value : new Date(e.target.value).toISOString()); }}/></label></div>
    {event.allDay && <p className="form-hint">All-day end dates are exclusive: choose the following day for a one-day event.</p>}
    <label>Location<input value={event.location} disabled={readOnly} onChange={e => field('location', e.target.value)} placeholder="Add a place or meeting link"/></label><label>Notes<textarea rows={5} value={event.description} disabled={readOnly} onChange={e => field('description', e.target.value)} placeholder="Anything you’ll need for this event"/></label>
    </div><footer className="modal-footer">{event.id && !readOnly && <button type="button" className="text-button danger" disabled={busy} onClick={async () => { if (!confirmDelete) { setConfirmDelete(true); return; } setBusy(true); try { await api.deleteEvent(event); onSaved('Event deleted'); onClose(); } catch (e) { onError(e); } finally { setBusy(false); } }}><Trash2 size={16}/>{confirmDelete ? 'Confirm delete' : 'Delete event'}</button>}<span className="spacer"/><button type="button" className="secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy || readOnly || !calendars.length}>{busy && <Loader2 className="spin" size={16}/>}Save event</button></footer>
  </form></Modal>;
}
export function Settings({ accounts, signatureAccounts, config, demo, onClose, onConnected, onConfig, onDemo, onError }: { accounts: Account[]; signatureAccounts: Account[]; config: Config; demo: boolean; onClose: () => void; onConnected: () => Promise<void>; onConfig: (c: Config) => void; onDemo: (demo: boolean) => void; onError: (e: unknown) => void }) {
  const [busy, setBusy] = useState(''); const [key, setKey] = useState(''); const [model, setModel] = useState(config.geminiModel); const [saved, setSaved] = useState(false);
  async function action(name: string, fn: () => Promise<void>) { setBusy(name); try { await fn(); } catch (e) { onError(e); } finally { setBusy(''); } }
  return <Modal title="Make it yours" className="settings" onClose={onClose}><div className="settings-content">
    <section><h3>Google accounts</h3><p>Bring your Gmail and Google Calendar accounts together.</p>{!window.desktop && <div className="setup-note">You’re viewing the browser demo. Open the rAIzorMail Mac app to connect Google accounts.</div>}
    {accounts.map(a => <div className="account-setting" key={a.id}><span className="account-dot" style={{ background: a.color }}/><div><strong>{a.name}</strong><small>{a.email}</small></div><button className="text-button" disabled={!!busy} onClick={() => action('disconnect', async () => { await window.desktop!.invoke('disconnect', a.id); await onConnected(); })}>Disconnect</button></div>)}
    <div className="setting-actions"><button className="primary" disabled={!window.desktop || !config.googleConfigured || !!busy} onClick={() => action('connect', async () => { await window.desktop!.invoke('connectGoogle'); await onConnected(); })}>{busy === 'connect' ? <Loader2 size={16} className="spin"/> : <Plus size={16}/>}Connect Google account</button></div>
    {busy === 'connect' && <p className="form-hint">Finish signing in with Google in your browser. This can take a moment.</p>}
    <details open={!config.googleConfigured}><summary>First-time Google setup {config.googleConfigured && <Check size={14}/>}</summary><ol><li>Open <a href="https://console.cloud.google.com/apis/library" target="_blank" rel="noreferrer">Google Cloud <ExternalLink size={11}/></a>. Create a project and enable Gmail API and Google Calendar API.</li><li>Configure Google Auth Platform. For a personal external app, add your Gmail addresses as test users.</li><li>Create an OAuth client with application type <strong>Desktop app</strong>. Download its JSON file.</li><li>Import that file below, then connect each account.</li></ol><button className="secondary" disabled={!window.desktop || !!busy} onClick={() => action('import', async () => { const c = await window.desktop!.invoke<Config>('importGoogle'); onConfig(c); })}>{config.googleConfigured ? 'Replace OAuth credentials' : 'Import Google OAuth JSON'}</button><p className="form-hint">Google apps in testing may require periodic reconnection. Credentials are stored encrypted on this Mac.</p></details></section>
    <SignatureSettings accounts={signatureAccounts} api={getAPI(demo)} onError={onError}/>
    <section><h3>Gemini AI</h3><p>Search mail and calendar events in natural language, or draft and revise emails. Searches send only your request and date context. Writing help sends the draft text you choose to work on. Your API key stays encrypted on this Mac.</p><label>Gemini API key<input type="password" autoComplete="off" value={key} onChange={e => { setKey(e.target.value); setSaved(false); }} placeholder={config.geminiConfigured ? 'A key is saved securely' : 'Paste your Gemini API key'}/></label><label>Model<input value={model} onChange={e => { setModel(e.target.value); setSaved(false); }} placeholder="gemini-3.8-flash"/></label><div className="setting-actions"><button className="secondary" disabled={!window.desktop || !!busy || (!key && !config.geminiConfigured)} onClick={() => action('gemini', async () => { setSaved(false); onConfig(await window.desktop!.invoke<Config>('saveGemini', { key, model })); setKey(''); await window.desktop!.invoke('testGemini'); setSaved(true); })}>{saved ? <Check size={14}/> : null}{saved ? 'Connected to Gemini' : busy === 'gemini' ? 'Testing…' : 'Save & test Gemini'}</button><a href="https://aistudio.google.com/api-keys" target="_blank" rel="noreferrer">Get an API key <ArrowUpRight size={13}/></a></div></section>
    <section className="demo-setting"><div><h3>Sample mailbox</h3><p>Explore mail and calendar with fictional messages.</p></div><button className="secondary" onClick={() => { onDemo(!demo); onClose(); }} disabled={demo && !accounts.length}>{demo ? 'Use connected accounts' : 'Open demo'}</button></section>
    <p className="form-hint">rAIzorMail 0.1 · Made for your Mac, by rAIzor crest.</p>
  </div></Modal>;
}
